[theme]
primaryColor="#edddcd"  # Greenish accent, like Grok/GitHub dark
backgroundColor="#edddcd"  # Almost black background
secondaryBackgroundColor="#f64c13"  # Slightly lighter for cards/panels
textColor="#0f9d58"  
font="sans serif"
