[theme]
primaryColor="#edddcd"  # Greenish accent, like Grok/GitHub dark
backgroundColor="#edddcd"  # Almost black background
secondaryBackgroundColor="#edddcd"  # Slightly lighter for cards/panels
textColor="#000000	"  
font="sans serif"
